check deployment connection

diff --git a/.ado/cicd.yml b/.ado/cicd.yml
--- a/.ado/cicd.yml
+++ b/.ado/cicd.yml
@@ -59,110 +59,155 @@ stages:
   #             echo "Validation successful: Directory '$DIR_PATH' is present."
   #           displayName: Validate Parameterized Directory
 
-  - stage: building_${{ parameters.directoryPath }}_image
-    jobs:
-      - job: build_and_tag_image
-        displayName: Build Docker Image and Push to Docker Hub
-        steps:
-          - checkout: self
-          - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
-            displayName: Print DOCKER_USERNAME
-          - script: ls -la ${{ parameters.directoryPath }}
-            displayName: List Files in the Directory
-          - task: Docker@2
-            displayName: Build and Push Docker Image
-            inputs:
-              containerRegistry: docker-hub-connection
-              repository: $(DOCKER_USERNAME)/preprocessing
-              command: buildAndPush
-              Dockerfile: ${{ parameters.directoryPath }}/Dockerfile
-              tags: |
-                latest
-                ${{ parameters.version }}
-#                $(Build.SourceBranchName)
+#   - stage: building_${{ parameters.directoryPath }}_image
+#     jobs:
+#       - job: build_and_tag_image
+#         displayName: Build Docker Image and Push to Docker Hub
+#         steps:
+#           - checkout: self
+#           - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
+#             displayName: Print DOCKER_USERNAME
+#           - script: ls -la ${{ parameters.directoryPath }}
+#             displayName: List Files in the Directory
+#           - task: Docker@2
+#             displayName: Build and Push Docker Image
+#             inputs:
+#               containerRegistry: docker-hub-connection
+#               repository: $(DOCKER_USERNAME)/preprocessing
+#               command: buildAndPush
+#               Dockerfile: ${{ parameters.directoryPath }}/Dockerfile
+#               tags: |
+#                 latest
+#                 ${{ parameters.version }}
+# #                $(Build.SourceBranchName)
 
-  - stage: PackageHelmChart
-    jobs:
-      - job: create_helm_pkg
-        displayName: Package helm charts and artifact.
-        steps:
-          - checkout: HelmCharts
-            persistCredentials: true
+#   - stage: PackageHelmChart
+#     jobs:
+#       - job: create_helm_pkg
+#         displayName: Package helm charts and artifact.
+#         steps:
+#           - checkout: HelmCharts
+#             persistCredentials: true
 
-          - checkout: self
-            displayName: Checking out complete Repo
+#           - checkout: self
+#             displayName: Checking out complete Repo
 
-          - script: |
-              yq eval '.version = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
-              yq eval '.appVersion = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
-              cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
-            displayName: "Updated ${{ parameters.directoryPath }} Chart.yaml"
+#           - script: |
+#               yq eval '.version = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
+#               yq eval '.appVersion = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
+#               cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
+#             displayName: "Updated ${{ parameters.directoryPath }} Chart.yaml"
 
-          - script: |
-              yq eval '.image.repository = "amitgupta2533/${{ parameters.directoryPath }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
-              yq eval '.image.tag = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
-              cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
-            displayName: "Updated ${{ parameters.directoryPath }} values.yaml"
+#           - script: |
+#               yq eval '.image.repository = "amitgupta2533/${{ parameters.directoryPath }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
+#               yq eval '.image.tag = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
+#               cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
+#             displayName: "Updated ${{ parameters.directoryPath }} values.yaml"
 
-          - task: HelmInstaller@1
-            displayName: Helm installer
-            inputs: 
-              helmVersionToInstall: 3.16.3
+#           - task: HelmInstaller@1
+#             displayName: Helm installer
+#             inputs: 
+#               helmVersionToInstall: 3.16.3
           
-          - script: |
-              helm package mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service --destination mlops-windoutput-helm/helm/packages
-              echo "Helm chart packaged successfully in 'mlops-windoutput-helm/helm/packages'"
-            displayName: "Updated and Packaged ${{ parameters.directoryPath }} Helm Chart"
+#           - script: |
+#               helm package mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service --destination mlops-windoutput-helm/helm/packages
+#               echo "Helm chart packaged successfully in 'mlops-windoutput-helm/helm/packages'"
+#             displayName: "Updated and Packaged ${{ parameters.directoryPath }} Helm Chart"
 
-          - task: PublishBuildArtifacts@1
-            inputs:
-              pathToPublish: mlops-windoutput-helm/helm/packages
-              artifactName: helm-chart-artifact
-              publishLocation: Container
+#           - task: PublishBuildArtifacts@1
+#             inputs:
+#               pathToPublish: mlops-windoutput-helm/helm/packages
+#               artifactName: helm-chart-artifact
+#               publishLocation: Container
 
-  - stage: PushFileToChartsRepo
-    jobs:
-      - job: push_file
-        steps:
-          - checkout: HelmCharts
-            persistCredentials: true
-          - checkout: self
-            displayName: Checking out complete Repo
+#   - stage: PushFileToChartsRepo
+#     jobs:
+#       - job: push_file
+#         steps:
+#           - checkout: HelmCharts
+#             persistCredentials: true
+#           - checkout: self
+#             displayName: Checking out complete Repo
             
-          - task: DownloadBuildArtifacts@0
-            inputs:
-              buildType: 'current'
-              downloadType: 'specific'
-              artifactName: 'helm-chart-artifact'
-              downloadPath: '$(Pipeline.Workspace)/helm-chart'
+#           - task: DownloadBuildArtifacts@0
+#             inputs:
+#               buildType: 'current'
+#               downloadType: 'specific'
+#               artifactName: 'helm-chart-artifact'
+#               downloadPath: '$(Pipeline.Workspace)/helm-chart'
           
-          - task: HelmInstaller@1
-            displayName: Helm installer
-            inputs: 
-              helmVersionToInstall: 3.16.3
+#           - task: HelmInstaller@1
+#             displayName: Helm installer
+#             inputs: 
+#               helmVersionToInstall: 3.16.3
 
-          - script: |
-              cd helm-charts
-              git status
-              git config --global user.email pipeline@demo.com
-              git config --global user.name "Pipeline"
-              git checkout main || git checkout -b main
+#           - script: |
+#               cd helm-charts
+#               git status
+#               git config --global user.email pipeline@demo.com
+#               git config --global user.name "Pipeline"
+#               git checkout main || git checkout -b main
               
-              # Check if the artifact file exists
-              if [ -f "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ]; then
-                  echo "File found. Copying to the target directory..."
-                  mkdir -p ${{ parameters.directoryPath }}
-                  cp "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ${{ parameters.directoryPath }}/
-                  echo "File successfully copied"
-              else
-                  echo "File ${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz not found in artifact"
-                  exit 1
-              fi
-              helm repo index ${{ parameters.directoryPath }} --url https://analyst-amit.github.io/helm-charts/${{ parameters.directoryPath }}
-              git add -A
-              git commit -m "Added latest ${{ parameters.directoryPath }} file"
-              git push -u origin main
-            displayName: Create, Commit, and Push
+#               # Check if the artifact file exists
+#               if [ -f "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ]; then
+#                   echo "File found. Copying to the target directory..."
+#                   mkdir -p ${{ parameters.directoryPath }}
+#                   cp "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ${{ parameters.directoryPath }}/
+#                   echo "File successfully copied"
+#               else
+#                   echo "File ${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz not found in artifact"
+#                   exit 1
+#               fi
+#               helm repo index ${{ parameters.directoryPath }} --url https://analyst-amit.github.io/helm-charts/${{ parameters.directoryPath }}
+#               git add -A
+#               git commit -m "Added latest ${{ parameters.directoryPath }} file"
+#               git push -u origin main
+#             displayName: Create, Commit, and Push
+  
+  - stage: CD-deploy-qa
+    jobs:
+      - job: deploy-qa
+        steps:          
+          # Package and deploy Helm charts v0
+          # Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands.
+          - task: HelmDeploy@0
+            inputs:
+            # Kubernetes Cluster
+              connectionType: 'Kubernetes Service Connection' # 'Azure Resource Manager' | 'Kubernetes Service Connection' | 'None'. Required when command != logout && command != package && command != save. Connection Type. Default: Azure Resource Manager.
+              kubernetesServiceConnection: azure-pipeline-sa
+              namespace: env-qa
+            # Commands
+              command: 'ls' # 'create' | 'delete' | 'expose' | 'get' | 'init' | 'install' | 'login' | 'logout' | 'ls' | 'package' | 'rollback' | 'save' | 'upgrade' | 'uninstall'. Required. Command. Default: ls.
+              # chartType: 'Name' # 'Name' | 'FilePath'. Required when command == install || command == upgrade. Chart Type. Default: Name.
+              # chartName: # string. Required when chartType == Name. Chart Name. 
+              # chartPath: # string. Required when chartType == FilePath || command == package. Chart Path. 
+              # chartVersion: # string. Alias: version. Optional. Use when command == package || command == install || command == upgrade. Version. 
+              #releaseName: # string. Optional. Use when command == install || command == upgrade. Release Name. 
+              #overrideValues: # string. Optional. Use when command == install || command == upgrade. Set Values. 
+              #valueFile: # string. Optional. Use when command == install || command == upgrade. Value File. 
+              #destination: '$(Build.ArtifactStagingDirectory)' # string. Optional. Use when command == package. Destination. Default: $(Build.ArtifactStagingDirectory).
+              #canaryimage: false # boolean. Optional. Use when command == init. Use canary image version. Default: false.
+              #upgradetiller: true # boolean. Optional. Use when command == init. Upgrade Tiller. Default: true.
+              #updatedependency: false # boolean. Optional. Use when command == install || command == package. Update Dependency. Default: false.
+              #save: true # boolean. Optional. Use when command == package. Save. Default: true.
+              #install: true # boolean. Optional. Use when command == upgrade. Install if release not present. Default: true.
+              #recreate: false # boolean. Optional. Use when command == upgrade. Recreate Pods. Default: false.
+              #resetValues: false # boolean. Optional. Use when command == upgrade. Reset Values. Default: false.
+              #force: false # boolean. Optional. Use when command == upgrade. Force. Default: false.
+              #waitForExecution: true # boolean. Optional. Use when command == init || command == install || command == upgrade. Wait. Default: true.
+              #arguments: # string. Optional. Use when command != login && command != logout. Arguments. 
+              #chartNameForACR: # string. Required when command == save. Chart Name For Azure Container Registry. 
+              #chartPathForACR: # string. Required when command == save. Chart Path for Azure Container Registry. 
+            # TLS
+              #enableTls: false # boolean. Optional. Use when command != login && command != logout && command != package && command != save. Enable TLS. Default: false.
+              #caCert: # string. Required when enableTls == true && command != login && command != logout && command != package && command != save. CA certificate. 
+              #certificate: # string. Required when enableTls == true && command != login && command != logout && command != package && command != save. Certificate. 
+              #privatekey: # string. Required when enableTls == true && command != login && command != logout && command != package && command != save. Key. 
+            # Advanced
+              #tillernamespace: # string. Optional. Use when command != login && command != logout && command != package && command != save. Tiller namespace. 
+              #failOnStderr: false # boolean. Optional. Use when command != login && command != logout && command != package && command != save. Fail on Standard Error. Default: false.
+              #publishPipelineMetadata: true # boolean. Optional. Use when command != login && command != logout && command != package && command != save. Publish pipeline metadata. Default: true.
+
 
 
 
